# Generated by Django 4.2.7 on 2023-12-16 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=15)),
                ('desc', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=50)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Apartment', 'Apartment')], default='House', max_length=50)),
                ('sqft', models.IntegerField()),
                ('open_house', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_12', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_13', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_14', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_15', models.ImageField(blank=True, upload_to='photos/%Y/%2/%d/')),
                ('photo_16', models.ImageField(blank=True, upload_to='photos/%Y/%3/%d/')),
                ('photo_17', models.ImageField(blank=True, upload_to='photos/%Y/%4/%d/')),
                ('photo_18', models.ImageField(blank=True, upload_to='photos/%Y/%4/%d/')),
                ('photo_19', models.ImageField(blank=True, upload_to='photos/%Y/%4/%d/')),
                ('photo_20', models.ImageField(blank=True, upload_to='photos/%Y/%4/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('property_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('furniture_type', models.CharField(choices=[('Fully Furnished', 'Fully Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Unfurnished', 'Unfurnished')], default='Unfurnished', max_length=50)),
                ('tenant_type', models.CharField(blank=True, choices=[('Single men', 'Single Men'), ('Single women', 'Single Women'), ('Couples', 'Couples')], default=None, max_length=50, null=True)),
                ('Realtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
